name: ESPHome temperature and humidity sensor with OLED display

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      # CHANGEME: Set the filenames of your config files here:
      files: temp-humid-OLED.yaml
      # CHANGEME: Set the name of your project here:
      name: ESPHome temp humid OLED
